-- CORSIA: PK composta, niente auto-increment sul numero di corsia
CREATE TABLE CORSIA (
    num_corsia   INT        NOT NULL,
    id_casello   INT        NOT NULL,
    verso        VARCHAR(10)  NOT NULL,
    tipo_corsia  VARCHAR(20)  NOT NULL,
    is_closed    BOOLEAN      NOT NULL DEFAULT FALSE,
);

-- Per i 4 caselli creati prima (id 1..4)
INSERT INTO CORSIA (num_corsia, id_casello, verso, tipo_corsia, is_closed) VALUES
  -- CASELLO 1
  (1, 1, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 1, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 1, 'USCITA',  'TELEPASS', FALSE),
  (4, 1, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 2
  (1, 2, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 2, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 2, 'USCITA',  'TELEPASS', FALSE),
  (4, 2, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 3
  (1, 3, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 3, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 3, 'USCITA',  'TELEPASS', FALSE),
  (4, 3, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 4
  (1, 4, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 4, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 4, 'USCITA',  'TELEPASS', FALSE),
  (4, 4, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 5
  (1, 5, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 5, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 5, 'USCITA',  'TELEPASS', FALSE),
  (4, 5, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 6
  (1, 6, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 6, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 6, 'USCITA',  'TELEPASS', FALSE),
  (4, 6, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 7
  (1, 7, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 7, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 7, 'USCITA',  'TELEPASS', FALSE),
  (4, 7, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 8
  (1, 8, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 8, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 8, 'USCITA',  'TELEPASS', FALSE),
  (4, 8, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 9
  (1, 9, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 9, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 9, 'USCITA',  'TELEPASS', FALSE),
  (4, 9, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 10
  (1, 10, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 10, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 10, 'USCITA',  'TELEPASS', FALSE),
  (4, 10, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 11
  (1, 11, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 11, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 11, 'USCITA',  'TELEPASS', FALSE),
  (4, 11, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 12
  (1, 12, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 12, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 12, 'USCITA',  'TELEPASS', FALSE),
  (4, 12, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 13
  (1, 13, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 13, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 13, 'USCITA',  'TELEPASS', FALSE),
  (4, 13, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 14
  (1, 14, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 14, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 14, 'USCITA',  'TELEPASS', FALSE),
  (4, 14, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 15
  (1, 15, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 15, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 15, 'USCITA',  'TELEPASS', FALSE),
  (4, 15, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 16
  (1, 16, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 16, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 16, 'USCITA',  'TELEPASS', FALSE),
  (4, 16, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 17
  (1, 17, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 17, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 17, 'USCITA',  'TELEPASS', FALSE),
  (4, 17, 'USCITA',  'MANUALE',    FALSE),
  
  -- CASELLO 18
  (1, 18, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 18, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 18, 'USCITA',  'TELEPASS', FALSE),
  (4, 18, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 19
  (1, 19, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 19, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 19, 'USCITA',  'TELEPASS', FALSE),
  (4, 19, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 20 
  (1, 20, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 20, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 20, 'USCITA',  'TELEPASS', FALSE),
  (4, 20, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 21 
  (1, 21, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 21, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 21, 'USCITA',  'TELEPASS', FALSE),
  (4, 21, 'USCITA',  'MANUALE',    FALSE),

   -- CASELLO 22 
  (1, 22, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 22, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 22, 'USCITA',  'TELEPASS', FALSE),
  (4, 22, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 23 
  (1, 23, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 23, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 23, 'USCITA',  'TELEPASS', FALSE),
  (4, 23, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 24 
  (1, 24, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 24, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 24, 'USCITA',  'TELEPASS', FALSE),
  (4, 24, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 25
  (1, 25, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 25, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 25, 'USCITA',  'TELEPASS', FALSE),
  (4, 25, 'USCITA',  'MANUALE',    FALSE),

   -- CASELLO 26
  (1, 26, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 26, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 26, 'USCITA',  'TELEPASS', FALSE),
  (4, 26, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 27
  (1, 27, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 27, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 27, 'USCITA',  'TELEPASS', FALSE),
  (4, 27, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 28
  (1, 28, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 28, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 28, 'USCITA',  'TELEPASS', FALSE),
  (4, 28, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 29
  (1, 29, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 29, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 29, 'USCITA',  'TELEPASS', FALSE),
  (4, 29, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 30
  (1, 30, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 30, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 30, 'USCITA',  'TELEPASS', FALSE),
  (4, 30, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 31
  (1, 31, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 31, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 31, 'USCITA',  'TELEPASS', FALSE),
  (4, 31, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 32
  (1, 32, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 32, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 32, 'USCITA',  'TELEPASS', FALSE),
  (4, 32, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 33
  (1, 33, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 33, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 33, 'USCITA',  'TELEPASS', FALSE),
  (4, 33, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 34
  (1, 34, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 34, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 34, 'USCITA',  'TELEPASS', FALSE),
  (4, 34, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 35
  (1, 35, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 35, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 35, 'USCITA',  'TELEPASS', FALSE),
  (4, 35, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 36
  (1, 36, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 36, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 36, 'USCITA',  'TELEPASS', FALSE),
  (4, 36, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 37
  (1, 37, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 37, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 37, 'USCITA',  'TELEPASS', FALSE),
  (4, 37, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 38
  (1, 38, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 38, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 38, 'USCITA',  'TELEPASS', FALSE),
  (4, 38, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 39
  (1, 39, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 39, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 39, 'USCITA',  'TELEPASS', FALSE),
  (4, 39, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 40
  (1, 40, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 40, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 40, 'USCITA',  'TELEPASS', FALSE),
  (4, 40, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 41
  (1, 41, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 41, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 41, 'USCITA',  'TELEPASS', FALSE),
  (4, 41, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 42
  (1, 42, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 42, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 42, 'USCITA',  'TELEPASS', FALSE),
  (4, 42, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 43
  (1, 43, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 43, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 43, 'USCITA',  'TELEPASS', FALSE),
  (4, 43, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 44
  (1, 44, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 44, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 44, 'USCITA',  'TELEPASS', FALSE),
  (4, 44, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 45
  (1, 45, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 45, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 45, 'USCITA',  'TELEPASS', FALSE),
  (4, 45, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 46
  (1, 46, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 46, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 46, 'USCITA',  'TELEPASS', FALSE),
  (4, 46, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 47
  (1, 47, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 47, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 47, 'USCITA',  'TELEPASS', FALSE),
  (4, 47, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 48
  (1, 48, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 48, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 48, 'USCITA',  'TELEPASS', FALSE),
  (4, 48, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 49
  (1, 49, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 49, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 49, 'USCITA',  'TELEPASS', FALSE),
  (4, 49, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 50
  (1, 50, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 50, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 50, 'USCITA',  'TELEPASS', FALSE),
  (4, 50, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 51
  (1, 51, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 51, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 51, 'USCITA',  'TELEPASS', FALSE),
  (4, 51, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 52
  (1, 52, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 52, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 52, 'USCITA',  'TELEPASS', FALSE),
  (4, 52, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 53
  (1, 53, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 53, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 53, 'USCITA',  'TELEPASS', FALSE),
  (4, 53, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 54
  (1, 54, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 54, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 54, 'USCITA',  'TELEPASS', FALSE),
  (4, 54, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 55
  (1, 55, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 55, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 55, 'USCITA',  'TELEPASS', FALSE),
  (4, 55, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 56
  (1, 56, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 56, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 56, 'USCITA',  'TELEPASS', FALSE),
  (4, 56, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 57
  (1, 57, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 57, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 57, 'USCITA',  'TELEPASS', FALSE),
  (4, 57, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 58
  (1, 58, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 58, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 58, 'USCITA',  'TELEPASS', FALSE),
  (4, 58, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 59
  (1, 59, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 59, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 59, 'USCITA',  'TELEPASS', FALSE),
  (4, 59, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 60
  (1, 60, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 60, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 60, 'USCITA',  'TELEPASS', FALSE),
  (4, 60, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 61
  (1, 61, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 61, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 61, 'USCITA',  'TELEPASS', FALSE),
  (4, 61, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 62
  (1, 62, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 62, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 62, 'USCITA',  'TELEPASS', FALSE),
  (4, 62, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 63
  (1, 63, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 63, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 63, 'USCITA',  'TELEPASS', FALSE),
  (4, 63, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 64
  (1, 64, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 64, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 64, 'USCITA',  'TELEPASS', FALSE),
  (4, 64, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 65
  (1, 65, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 65, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 65, 'USCITA',  'TELEPASS', FALSE),
  (4, 65, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 66
  (1, 66, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 66, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 66, 'USCITA',  'TELEPASS', FALSE),
  (4, 66, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 67
  (1, 67, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 67, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 67, 'USCITA',  'TELEPASS', FALSE),
  (4, 67, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 68
  (1, 68, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 68, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 68, 'USCITA',  'TELEPASS', FALSE),
  (4, 68, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 69
  (1, 69, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 69, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 69, 'USCITA',  'TELEPASS', FALSE),
  (4, 69, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 70
  (1, 70, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 70, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 70, 'USCITA',  'TELEPASS', FALSE),
  (4, 70, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 71
  (1, 71, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 71, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 71, 'USCITA',  'TELEPASS', FALSE),
  (4, 71, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 72
  (1, 72, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 72, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 72, 'USCITA',  'TELEPASS', FALSE),
  (4, 72, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 73
  (1, 73, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 73, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 73, 'USCITA',  'TELEPASS', FALSE),
  (4, 73, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 74
  (1, 74, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 74, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 74, 'USCITA',  'TELEPASS', FALSE),
  (4, 74, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 75
  (1, 75, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 75, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 75, 'USCITA',  'TELEPASS', FALSE),
  (4, 75, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 76
  (1, 76, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 76, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 76, 'USCITA',  'TELEPASS', FALSE),
  (4, 76, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 77
  (1, 77, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 77, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 77, 'USCITA',  'TELEPASS', FALSE),
  (4, 77, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 78
  (1, 78, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 78, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 78, 'USCITA',  'TELEPASS', FALSE),
  (4, 78, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 79
  (1, 79, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 79, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 79, 'USCITA',  'TELEPASS', FALSE),
  (4, 79, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 80
  (1, 80, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 80, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 80, 'USCITA',  'TELEPASS', FALSE),
  (4, 80, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 81
  (1, 81, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 81, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 81, 'USCITA',  'TELEPASS', FALSE),
  (4, 81, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 82
  (1, 82, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 82, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 82, 'USCITA',  'TELEPASS', FALSE),
  (4, 82, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 83
  (1, 83, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 83, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 83, 'USCITA',  'TELEPASS', FALSE),
  (4, 83, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 84
  (1, 84, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 84, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 84, 'USCITA',  'TELEPASS', FALSE),
  (4, 84, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 85
  (1, 85, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 85, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 85, 'USCITA',  'TELEPASS', FALSE),
  (4, 85, 'USCITA',  'MANUALE',    FALSE),
  
  -- CASELLO 86
  (1, 86, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 86, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 86, 'USCITA',  'TELEPASS', FALSE),
  (4, 86, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 87
  (1, 87, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 87, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 87, 'USCITA',  'TELEPASS', FALSE),
  (4, 87, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 88
  (1, 88, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 88, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 88, 'USCITA',  'TELEPASS', FALSE),
  (4, 88, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 89
  (1, 89, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 89, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 89, 'USCITA',  'TELEPASS', FALSE),
  (4, 89, 'USCITA',  'MANUALE',    FALSE),
  
  -- CASELLO 90
  (1, 90, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 90, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 90, 'USCITA',  'TELEPASS', FALSE),
  (4, 90, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 91
  (1, 91, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 91, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 91, 'USCITA',  'TELEPASS', FALSE),
  (4, 91, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 92
  (1, 92, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 92, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 92, 'USCITA',  'TELEPASS', FALSE),
  (4, 92, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 93
  (1, 93, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 93, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 93, 'USCITA',  'TELEPASS', FALSE),
  (4, 93, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 94
  (1, 94, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 94, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 94, 'USCITA',  'TELEPASS', FALSE),
  (4, 94, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 95
  (1, 95, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 95, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 95, 'USCITA',  'TELEPASS', FALSE),
  (4, 95, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 96
  (1, 96, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 96, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 96, 'USCITA',  'TELEPASS', FALSE),
  (4, 96, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 97
  (1, 97, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 97, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 97, 'USCITA',  'TELEPASS', FALSE),
  (4, 97, 'USCITA',  'MANUALE',    FALSE),
  
  -- CASELLO 98
  (1, 98, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 98, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 98, 'USCITA',  'TELEPASS', FALSE),
  (4, 98, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 99
  (1, 99, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 99, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 99, 'USCITA',  'TELEPASS', FALSE),
  (4, 99, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 100
  (1, 100, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 100, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 100, 'USCITA',  'TELEPASS', FALSE),
  (4, 100, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 101
  (1, 101, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 101, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 101, 'USCITA',  'TELEPASS', FALSE),
  (4, 101, 'USCITA',  'MANUALE',    FALSE),
  
  -- CASELLO 102
  (1, 102, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 102, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 102, 'USCITA',  'TELEPASS', FALSE),
  (4, 102, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 103
  (1, 103, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 103, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 103, 'USCITA',  'TELEPASS', FALSE),
  (4, 103, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 104
  (1, 104, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 104, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 104, 'USCITA',  'TELEPASS', FALSE),
  (4, 104, 'USCITA',  'MANUALE',    FALSE),

  -- CASELLO 105
  (1, 105, 'ENTRATA', 'TELEPASS', FALSE),
  (2, 105, 'ENTRATA', 'MANUALE',    FALSE),
  (3, 105, 'USCITA',  'TELEPASS', FALSE),
  (4, 105, 'USCITA',  'MANUALE',    FALSE);
